### ISSUE TITLE
I download an autorun sb application to the board and terminal stop response

### ISSUE THREAD

**Issue by SongDingQing** [LairdCP/BL653-Applications#2]
![image](https://user-images.githubusercontent.com/86466959/168890761-dba7fd8b-7d13-40bc-a8e0-b41896839281.png)
I was trying to setup the VSP service and it worked (I can send a message from my phone to the board and it shows on the terminal)
Afterward, I tried to load another application, it all shows timeout. 
What happened here, is there anything I can do? I tried ticking and unticking break and reset botton but none of them worked.

**Comment by thedjnK** [comment]
You probably have an autorun application loaded, if you untick DTR, then enable BREAK for 2 seconds and disable it, you will be back into interactive mode whereby you can clear the module using `at&f*` and load a new application
